### ISSUE TITLE
.env

### ISSUE THREAD

**Issue by Jes-debug** [Just-Msv/anti-raid-bot#1]
Can you make the token .env?

**Comment by Just-Msv** [comment]
U can Put the All Value in the config.py . no need of .env

**Comment by Jes-debug** [comment]
yeah but i use replit, it makes my project public

**Comment by Jes-debug** [comment]
hello?

**Comment by Jes-debug** [comment]
can u just tell me how to make bot.run .env? i dont code with python often

**Comment by Jes-debug** [comment]
nevermind i got it
